name: Release to PyPI

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - name: Add Poetry to path
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - name: Install venv
        working-directory: ./package
        run: |
          poetry install
          poetry config http-basic.pypi ${{ secrets.POETRY_HTTP_BASIC_PYPI_USERNAME }} ${{ secrets.POETRY_HTTP_BASIC_PYPI_PASSWORD }}
      - name: Publish package
        working-directory: ./package
        run: |
          poetry version patch
          poetry publish --build
